- name: Create OpenDMARC socket directory
  become: yes
  ansible.builtin.file:
    path: /var/spool/postfix/opendmarc
    state: directory
    owner: "{{ mailserver_opendmarc_user | default('opendmarc') }}"
    group: "{{ mailserver_opendmarc_group | default('opendmarc') }}"
    mode: 750

- name: Create OpenDMARC log directory
  become: yes
  ansible.builtin.file:
    path: /var/log/opendmarc
    state: directory
    owner: "{{ mailserver_opendmarc_user | default('opendmarc') }}"
    group: "{{ mailserver_opendmarc_group | default('opendmarc') }}"
    mode: 750

# TODO: This can probably be done with ansible.builtin.user
- name: Add postfix user to dkimpy-milter group
  become: yes
  ansible.builtin.shell:
    cmd: /usr/sbin/usermod -aG opendmarc postfix

- name: Configure opendmarc
  become: yes
  ansible.builtin.template:
    src: opendmarc.conf.j2
    dest: /etc/opendmarc.conf
  notify: restart_opendmarc
