- name: 'Generate LDAP bind password for {{ _create_domain.name }}'
  ansible.builtin.set_fact:
    _ldap_bind_password: "{{ lookup('community.general.random_string', length=40, override_special=special_list) }}"
  vars:
    special_list: '-_=+()[]{},./?!@#$^~:'
  when: _create_domain.backend_type == 'LDAP'

- name: 'Setup LDAP credentials for {{ _create_domain.name }}'
  ansible.builtin.include_tasks: tasks/ldap-create-cycle-user-password.yaml
  vars:
    _ldap:
      uri: '{{ _create_domain.backend_uri }}'
      ca_path: '{{ ldap_servers[_create_domain.ldap_host].ca_path }}'
      bind_user: '{{ ldap_servers[_create_domain.ldap_host].bind_user }}'
      bind_password: '{{ ldap_servers[_create_domain.ldap_host].bind_password }}'
      dn: '{{ _create_domain.ldap_bind_dn }}'
      uid: '{{ _create_domain.ldap_uid }}'
      password: '{{ _ldap_bind_password }}'
  when: _create_domain.backend_type == 'LDAP'

- name: 'Create Domain {{ _create_domain.name }}'
  become: yes
  community.mysql.mysql_query:
    login_unix_socket: /run/mysqld/mysqld.sock
    login_db: '{{ mailserver_db_name }}'
    query: >
      insert into `virtual_domains` set
      `name` = %(name)s,
      `backend_type` = %(backend_type)s,
      `backend_uri` = %(backend_uri)s,
      `ldap_bind_dn` = %(ldap_bind_dn)s,
      `ldap_bind_password` = %(ldap_bind_password)s,
      `ldap_base_dn` = %(ldap_base_dn)s,
      `ldap_sync_cron` = %(ldap_sync_cron)s,
      `allow_primary_password` = %(allow_primary_password)s
      on duplicate key update
      `backend_type` = %(backend_type)s,
      `backend_uri` = %(backend_uri)s,
      `ldap_bind_dn` = %(ldap_bind_dn)s,
      `ldap_bind_password` = %(ldap_bind_password)s,
      `ldap_base_dn` = %(ldap_base_dn)s,
      `ldap_sync_cron` = %(ldap_sync_cron)s,
      `allow_primary_password` = %(allow_primary_password)s
    named_args:
      name: '{{ _create_domain.name }}'
      backend_type: '{{ _create_domain.backend_type }}'
      backend_uri: "{{ _create_domain.backend_uri | default('') }}"
      ldap_bind_dn: "{{ _create_domain.ldap_bind_dn | default('') }}"
      ldap_bind_password: "{{ _ldap_bind_password | default('') }}"
      ldap_base_dn: "{{ _create_domain.ldap_base_dn | default('') }}"
      ldap_sync_cron: '{{ _create_domain.ldap_sync_cron | default(0) }}'
      allow_primary_password: '{{ _create_domain.allow_primary_password | default(0) }}'
  when: (_create_domain.state is defined and _create_domain.state == 'present') or _create_domain.state is not defined

# TODO: Decide if deletion is appropriate or just marking as inactive.
- name: 'Delete domain {{ _create_domain.name }}'
  ansible.builtin.debug:
    msg: Domain deletion is currently not implemented due to the potential harm of recursive config removal
  when: _create_domain.state is defined and _create_domain.state == 'absent'

