- name: Create User
  ansible.builtin.include_tasks: tasks/db-mailserver-user.yaml
  vars:
    _create_user:
      name: '{{ _user.0.name }}'
      email: '{{ _user.1.email }}'
      active: '{{ _user.1.active | default(1) }}'
      state:  "{{ _user.1.state | default('present') }}"

- name: Alias Loop
  ansible.builtin.include_tasks: tasks/db-mailserver-alias.yaml
  vars:
    _create_alias:
      name: '{{ _user.0.name }}'
      source: '{{ item.source }}'
      destination: '{{ _user.1.email }}'
      requires_identifier: '{{ item.requires_identifier | default(0) }}'
      state: "{{ item.state | default('present') }}"
  loop: '{{ _user.1.aliases }}'
  when: _user.1.aliases is defined

- name: Allowed Sender Loop
  ansible.builtin.include_tasks: tasks/db-mailserver-allowed-sender.yaml
  vars:
    _create_sender:
      name: '{{ _user.0.name }}'
      address: '{{ item.address }}'
      allowed_sender: '{{ _user.1.email }}'
      state: "{{ item.state | default('present') }}"
  loop: '{{ _user.1.allowed_sender }}'
  when: _user.1.allowed_sender is defined
