- name: Create temporary folder for sql schema
  become: yes
  ansible.builtin.tempfile:
    state: directory
  register: _temp_folder

- name: Copy mailserver schema
  become: yes
  ansible.builtin.copy:
    src: "files/{{ mailserver_db_migrations[schema_version.query_result[0][0]['value']] }}"
    dest: '{{ _temp_folder.path }}'

- name: Upgrade schema
  become: yes
  community.mysql.mysql_db:
    name: '{{ mailserver_db_name }}'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: import
    target: "{{ _temp_folder.path }}/{{ mailserver_db_migrations[schema_version.query_result[0][0]['value']] }}"

- name: Delete temporary folder
  become: yes
  ansible.builtin.file:
    path: '{{ _temp_folder.path }}'
    state: absent

- name: Determine schema version
  become: yes
  community.mysql.mysql_query:
    login_db: '{{ mailserver_db_name }}'
    query: SELECT `value` FROM `system_info` WHERE `key` = 'schema_version';
    login_unix_socket: /run/mysqld/mysqld.sock
  register: schema_version

- name: Loop
  ansible.builtin.include_tasks: tasks/db-schema-upgrade-loop.yaml
  when:
  - schema_version is succeeded
  - schema_version.rowcount == 1
  - schema_version.query_result[0][0]['value'] < {{ mailserver_db_schema_current }}
  - mailserver_db_migrations[schema_version.query_result[0][0]['value']] is defined

