# requires python3-ldap
- name: Verify bind user exists
  community.general.ldap_entry:
    server_uri: '{{ _ldap.uri }}'
    start_tls: yes
    ca_path: '{{ _ldap.ca_path }}'
    bind_dn: '{{ _ldap.bind_user }}'
    bind_pw: "{{ _ldap.bind_password }}"
    dn: '{{ _ldap.dn }}'
    objectClass:
    - account
    - simplesecurityobject
    attributes:
      uid: '{{ _ldap.uid }}'
      userPassword: '{{ _ldap.password }}'
      nsIdleTimeout: 0
  register: ldap_create
  delegate_to: localhost

- name: Cycle password
  community.general.ldap_passwd:
    server_uri: '{{ _ldap.uri }}'
    start_tls: yes
    ca_path: '{{ _ldap.ca_path }}'
    bind_dn: '{{ _ldap.bind_user }}'
    bind_pw: "{{ _ldap.bind_password }}"
    dn: '{{ _ldap.dn }}'
    passwd: '{{ _ldap.password }}'
  register: ldap_update
  when: not ldap_create.changed and not ldap_create.failed
  delegate_to: localhost
