- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot
  become: yes
  ansible.builtin.reboot:
  when: reboot_required.stat.exists == true
