---
# defaults file for mailserver
mailserver_db_name:               'mailserver'
mailserver_dovecot_user_readonly: 'dovecot-user'
mailserver_postfix_user_readonly: 'postfix-user'
mailserver_db_server:             '127.0.0.1'
mailserver_db_port:               3306
mailserver_db_schema_current:     20250312

# The following just enable the relevant section in master.cf 
# At this time they DO NOT actually configure postfix to use any of the services or install them.
mailserver_use_maildrop:  false
mailserver_use_uucp:      false
mailserver_use_ifmail:    false
mailserver_use_bsmtp:     false
mailserver_use_scalemail: false
mailserver_use_mailman:   false

mailserver_dkim_user:  'dkimpy-milter'
mailserver_dkim_group: 'dkimpy-milter'
mailserver_dkim_keypath: '/etc/dkimkeys/'

mailserver_maildir_base_path: '/var/mail/'

mailserver_recipient_delimiter: '-'

viesti_path: '/var/www/viesti-reports/'

viesti_db_name: 'viesti-reports'
viesti_db_user: 'viesti-reports'
viesti_db_host: 'localhost'
viesti_db_port: 3306

viesti_mail_smtp: '{{ ansible_host }}'
viesti_mail_smtp_port: 587
viesti_mail_imap: '{{ ansible_host }}'
viesti_mail_imap_port: 993

mailmanagement_path: '/var/www/mailmanagement/'

mailmanagement_db_user: 'mailmanagement-webui'
mailmanagement_db_host: '{{ mailserver_db_server }}'
mailmanagement_db_name: '{{ mailserver_db_name }}'
