---
# defaults file for provisioning_and_maintenance
sudo_present_command:
  Debian: dpkg -l sudo
  RedHat: rpm -q sudo

become_group:
  Debian: sudo
  RedHat: wheel

ssh_service:
  Debian: ssh
  RedHat: sshd

baseline_packages:
  Debian:
  - sudo
  RedHat:
  - sudo

pve_api_user: 'root@pam'
pve_snapshot_retention: 2
